SELECT COUNT(*)  
FROM PRODUCT_MAST;  

SELECT COUNT(*)  
FROM PRODUCT_MAST;  
WHERE RATE>=20; 

SELECT COUNT(DISTINCT COMPANY)  
FROM PRODUCT_MAST; 

SELECT SUM(COST)  
FROM PRODUCT_MAST; 

SELECT SUM(COST)  
FROM PRODUCT_MAST  
WHERE QTY>3  
GROUP BY COMPANY;  

SELECT AVG(COST)  
FROM PRODUCT_MAST;  

SELECT MAX(RATE)  
FROM PRODUCT_MAST;  

SELECT MIN(RATE)  
FROM PRODUCT_MAST;  
